/* art styles that go well with the app design */
export const ArtStyles = [
  'academic',
  'baroque',
  'dada',
  'futurism',
  'futurism',
  'high renaissance',
  'impressionism',
  'neoclassicism',
  'rococo',
  'romanticism',
  'surrealism',
  'symbolism',
  'synchromism',
  'suprematism',
  'ukiyo-e',
  'venetian school',
  'victorian',
];
